#pragma once

#include <string>
namespace raphen {
	namespace debug {

		//POD to hold the results of a profile generated by a timer
		struct ProfileResult
		{
			std::string name;
			long long start, end;
			uint32_t thread_id;
		};
	}
}